dubbo:
  application:
    name: goods-provide
    qos-enable: true
    qos-port: 33332
    qos-accept-foreign-ip: true
  registry:
    address: zookeeper://10.211.55.7:2181
  protocol:
    port: 20882
spring:
  datasource:
    url: jdbc:mysql://10.211.55.7:3306/gmail
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialization-mode: always
  jpa:
    show-sql: true
  redis:
    host: 10.211.55.7
mybatis:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
